### ISSUE TITLE
13G - Necromancer losing HP

### ISSUE THREAD

**Issue by gfnia** [Seraaron/roll20-character-sheets#13]
The necromancer gets rewarded by having negative HP, but he isnt supposed to lose starting HP or recovery healing, currently the CON bonus values are locked so I cant manually fix this.

Another small thing is that it would be nice if the macros on the Powers tab were a little more automatic, Im dming for a bunch of new players and it gets kinda slow having to help them remember what they have to do and whatnot, but besides that I prefer your sheet to the official one much more.

**Comment by Seraaron** [comment]
Sorry for being over a year late with this reply. I don't think there's anything I can do to make macros automatic, since there are too many powers to list individually and too many unique cases to make generalizations. You just have to write them yourself I'm afraid. That part of the point of the sheet though, total customizability. I'll look into the CON thing though, as I'm starting to get back into TTRPGs.

**Comment by Seraaron** [comment]
> The necromancer gets rewarded by having negative HP, but he isnt supposed to lose starting HP or recovery healing, currently the CON bonus values are locked so I cant manually fix this.

Hi, again and sorry about the lateness of getting back to you on this @gfnia ... I've looked into this and I don't think there's a simple way to implement this idea without resulting in what's called a 'breaking change' for everyone who's not currently playing a necromancer. Basically that means that if I were to implement this, everyone using the sheet would lose their currently calculated max HP.

It took me a while to find the rule you're talking about, so correct me if I'm wrong but it's the line "* Note, you don’t subtract the modifier from your base hp value if you have a negative Constitution modifier." for the Necromancer's (6 + CON mod*) x 3 Max HP. I have a couple of suggestions to help you do this manually:
- You could manutally edit the number 6 to be 6-(CON) so that (6-(CON)+CON) cancel out. (Eg. if your CON is -2, then 6-(-2) = 8 and therefore 8-2 = 6). Since this is all added up before it's multiplied by 3 it should work without a problem. You'll just have to edit the 6 every time your CON changes.
- You could use the custom Ability score in the sheet settings, by clicking the 'Other' button, and leave it's value at 10 (+0), and then just change CON to OTH from the dropdown in the Max HP calculator.
  - Alternatively, you could use the first option for max health, and call this other Ability 'Inverse Con.' or something, and set it to 12 (+1) to help implement the 'Wasting Away' adventurer feat.

I hope one of these two solutions is an acceptable compromise?

**Comment by gfnia** [comment]
Hey, no problem, thanks for even responding.

I went for the [first option](https://imgur.com/a/wnQ7Hco) and it worked great, the only "problem" is that bc I added blocked symbols the actual "Base HP" on the sheet [disappeared](https://imgur.com/a/UetHiz6), if I click on where it should be it restores, but that breaks the HP again. I'll just tell my player to not click there and just remember he has 6 base HP.

Thanks for the help, I appreciate it.
