### ISSUE TITLE
Tracking artha spent on beliefs and instincts

### ISSUE THREAD

**Issue by coreyhickson** [Seraaron/roll20-character-sheets#4]
In our game, we track artha spent on Beliefs and Instincts (as per Pg. 59 in Burning Wheel Gold Revised). With the instincts only letting us track fate, we don't have a way to track if we've spent persona or deeds working towards an instinct:

![image](https://user-images.githubusercontent.com/19170294/100948369-52fa2f80-34cd-11eb-8410-d1899e60aec8.png)

Great job on the new character sheet, it's awesome!

**Comment by Seraaron** [comment]
Hi, thanks.
Unfortunately, I'm not sure which rule you're referring to? Pg 59 is about Trait votes, and there's nothing on pg 71 about earning anything other than Fate from an Instinct. You don't really 'work towards' instincts afaik, they just come up and get you in trouble occasionally.

**Comment by coreyhickson** [comment]
Yeah I can include it here!

> Evolving Beliefs and Instincts
> Beliefs and Instincts are meant to evolve into traits throughout the course of play. Spending artha- which is discussed in the next chapter- on a Belief of Instinct is a good benchmark for the type of power level of a trait. The more artha spent, the more potent the trait.

**Comment by Seraaron** [comment]
I don't understand how you spend Artha on an instinct though?

**Comment by coreyhickson** [comment]
Right, so when you spend artha on a roll and you're working towards a Belief or following an Instinct, you can mark that artha on that Belief or Instinct.

**Comment by Seraaron** [comment]
Right. Yeah I see. I don't think I've ever heard of anyone maticulaously wanting to track that sort of thing until now though (BW has so much book keeping already). But with that said, the next update will include a 'Retired Beliefs and Instinct' in a new tab called 'Journal' which may be sufficiant for your use case. It has three slots on each repeating segment for tracking Artha.

Check the sheet out once it goes live next week and let me know if it suffices for what you want.

**Comment by coreyhickson** [comment]
I took a look at the retired section; it'll definitely work for Beliefs, thanks! I think for Instincts, we don't have a way to see which Persona/Deeds we may have spent towards them, though (as the main sheet still only shows Fate, so we can't track them while they're active)

**Comment by Seraaron** [comment]
Damn, I just wrote a really long reply trying to explain my design principles for the sheet, and then accidentally pressed Ctrl+W and closed the tab. I'll try summarise what I wrote:

- In my experience of playing BW on R20 for over 3 year now, and having introduced the game to about 8 new players, and spending a lot of time on the BW discord chatting with other users; the old design of the sheet was messy and annoying.
- There used to be 3 checkboxes for artha, but no one in my games ever used them to track artha _spent_; we would only use them as reminders to advocate for artha at the end of each session, and since you can't typically earn persona or deeds off of instincts, their presence was confusing.
- Now, with full artha trackers for Beliefs, but only fate trackers for Instincts, the visual heirachy reflects the reality of play: beliefs are more important than instincts.
- I did actually try implementing your idea in an earlier re-draft of the sheet, but so many number slots took up a lot of horizontal space and looked ugly and more confusing, implying even more bookeeping.
- You're the first person i've met who's ever mentioned this benchmarking rule (which i hesitate to even call a rule); and I prefer to design with rules representation in mind over implementation. Not even Luke Crane mentioned this when he contacted me a couple of weeks ago to add a few extra features he thought the sheet was missing.

So, my questions are this: How much do you actually use this rule? How often are you really spending persona (let alone deeds) on instincts? Would a work-around with what the sheet already has be sufficient (tracking it in brackets or `*italics*` at the end of each instinct text-box for example)?

Because basically I'm reluctant to add a feature which could potentially take up a lot of sheet real-estate, but which very few BW players (as I know them) would make use of. So can you think of a _clean_ way to add this, and do you know anyone else (outside of your play group) who would use this?
