### ISSUE TITLE
Some minor issues in 13th Age Glorantha sheet

### ISSUE THREAD

**Issue by speque** [Seraaron/roll20-character-sheets#6]
Hello! I just found your 13th Age Glorantha sheet and it looks great! However, while doing some testing I encountered some small issues and also some elements that were not that clear to me, so I'll list them here. Please tell if you would prefer separate issues instead.

Adventure/Combat-toggler: It is slightly out of place, I guess you could easily fix that by using `position: relative` here:  https://github.com/Seraaron/roll20-character-sheets/blob/master/13th%20Age%20Glorantha/src/13th_Age_Glorantha.html#L166

<img width="281" alt="Screenshot 2021-03-01 at 13 18 45" src="https://user-images.githubusercontent.com/186729/109490437-e58c7980-7a90-11eb-8dc6-983099d0e0ef.png">

Wounds & conditions toggle: I'm not quite sure what this character https://github.com/Seraaron/roll20-character-sheets/blob/master/13th%20Age%20Glorantha/src/13th_Age_Glorantha.css#L705 should look like, but it does not seem to work with my machine neither in Chrome or in Firefox. This also applies in other places it is used, for example Description/Macro toggle under Gifts/Powers.

<img width="482" alt="Screenshot 2021-03-01 at 13 30 48" src="https://user-images.githubusercontent.com/186729/109491550-5c764200-7a92-11eb-825e-4bb25fcb90f6.png">

HTML-entities in box titles: Some box titles contain HTML-elements, which display the code, not the character. In addition to the ones in picture there some other ones too, like Factions/Projects.

<img width="951" alt="Screenshot 2021-03-01 at 13 34 03" src="https://user-images.githubusercontent.com/186729/109492159-3309e600-7a93-11eb-9d07-824daa529ae3.png">

Miss damage: Miss damage for melee shows `@{level}` value key instead of evaluating it. Additionally I was wondering how to disable miss damage for classes that don't have it (Earth Priestess) or how to enable miss damage for ranged attack (Rebel).

<img width="492" alt="Screenshot 2021-03-01 at 13 47 16" src="https://user-images.githubusercontent.com/186729/109493328-fccd6600-7a94-11eb-950d-2beff5a9c0b8.png">

Weird multiplier: I was quite confused with this leftmost number here, what is it for? It seems to multiply the number of dice, but in which situation is that useful? 

<img width="224" alt="Screenshot 2021-03-01 at 13 50 41" src="https://user-images.githubusercontent.com/186729/109493531-52a20e00-7a95-11eb-918f-f6b5b7311fd8.png">

And then just a small note, although you can edit top bar labels, I felt the "Size" was a bit strange default value and even confusing for the players. In Gloranthan context for example "Cult" might be more useful?  

Thank you again for your work!

**Comment by speque** [comment]
Ok, after some investigating I found out the missing triangle icon is a font/OS related problem. The screenshot are taken with OSX, but on Windows the triangle shows up fine. Maybe some similar looking utf character would do the trick without depending on specific font?

I also forked the Roll20 repo and launched the testbed and in there there are no HTML entities in box titles, but when I go to Roll20 and launch a game then those entities show up. Maybe something funny in the build step?

**Comment by Seraaron** [comment]
Hi thanks for getting in touch.

Ah yeah,, it seems roll20 did some updates on the backend over christmas that's made html entities not display properly... changing the `value=""` to their normal display counterparts should fix that (e.g. `&sol;` —> `&`). none of these issues existed when I first published the sheet, at least on windows. I wasn't able to test on Mac.

Edit: Oh yeah, and the three I's like `III` were supposed to look like the "Harmony" rune. I tried to make it look good, but if it looks crap then feel free to just change it to an ampersand too `&`.

The missdamage, and other fields that use a mono-space font are for quoting values directly to chat when activated. So `@{level}` is correct, even though I know it looks weird. You can edit it to just be `0` for Earth Priestess. Similarly the default `0` for ranged miss attacks can be edited to `@{level}` or anything else you like. (Only things in round brackets are uneditable or auto-calc values).

I did a lot of things with this sheet to encourage customizability because I'm not a fan of 'rules are law' GMing methods, and exceptions and homebrew rulings can always be made. That's why there's a damage multiplier too, because who am I to say that you can't have a weapon that does 3D6 damage or whatever. You can read more about that design philosophy in the readme. (As a general rule, I tried to make as much of the sheet as possible to be editable, for use with Glorthana, normal 13th Age, and even custom games beyond that).

I was thinking Size would be for like your height or w/e, or how many tiles you take up on a map. Like humans are medium size (1x1 tile), trolls are large (2x2) I think? Correct me if there's a more game-official-term for that stat? We could change the default 4th custom info field to "Cult" if you think that makes more sense, but I put it as "God(s)" because I think Gloranthan's can worship more than one diety right? (And again, who am I to say otherwise 🤷 ).

The grunt build isn't identical to the roll20 build, so for major changes you'd have to get a roll20 pro account to do the final tweaking unfortunately. However, if you want to submit a PR here, I'll check it, and so long as it just contains minor formatting changes, we should be safe to push it to Roll20 live without a pro account.

If you want to make more substantial changes then let me know and one of us will need to get a pro account to do final testing.
